services:
    postgres:
        image: postgres:16
        container_name: postgres-local
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: chatapp
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:7
        container_name: redis-local
        command: ['redis-server', '--requirepass', 'redispassword']
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

volumes:
    postgres-data:
    redis-data:
